### ISSUE TITLE
[FEATURE REQUEST] Custom trigger tutorial + Support for newer watches

### ISSUE THREAD

**Issue by mhv75** [MattiaFochesato/AmazTools#1]
# Feature request

---

Instructions for using custom trigger are not available. Please provide instructions. I would love to test it out!

**Device info (please complete the following information):**
 - OS:  iOS 14.4.2
 - Device iPhone Xr 
 - App Version and Build number 1.2.5
 - Smartwatch model Amazfit band 5

**Comment by mhv75** [comment]
Much better!!! Sorry, I found it hard to choose

**Comment by MattiaFochesato** [comment]
Version 1.2.8 has just been released and adds support for custom triggers to all devices.
