### ISSUE TITLE
Watch Editor?

### ISSUE THREAD

**Issue by snjyr123** [MattiaFochesato/AmazTools#11]
Whenever I click on a watchface on the downloads tab, one of the options is watchface editor, which is a dead testflight link, does anyone mind telling me where this is from? I’ve been looking for an easy to use watchface editor.

**Comment by MattiaFochesato** [comment]
The watchface editor project has been canceled. It was very hard to maintain the compatibility with a lot of wearables and it wasn't easy to use on iPhone.
I'm really sorry. I'm going to remove the references of the watchface editor in the app.
