### ISSUE TITLE
Error 0x03 with mi band 6

### ISSUE THREAD

**Issue by Zzoomrus** [MattiaFochesato/AmazTools#2]
Any watch faces I tried to install give me this error 0x03.

- Device info:
OS: iOS 14.5.1
Device: iPhone 7 Plus
App Version and Build number: 1.2.7 (420)
Smartwatch model: MI band 6
Smartwatch firmware: 1.0.1.32

**Comment by MattiaFochesato** [comment]
I just released a new version on TestFlight which is supposed to fix this problem.

Thanks a lot for reporting. This error only occurs on older iPhones and appears to be fixed. Let me know!

**Comment by Zzoomrus** [comment]
Checked with 2 different watchfaces. Problem solved, thanks!
