### ISSUE TITLE
[BUG] Can’t Sync new watch face 

### ISSUE THREAD

**Issue by Frealaf** [MattiaFochesato/AmazTools#4]
# Submit a bug report
---

**Describe the bug**
When installing a new watch face,  after downloading it, the app gets stuck after trying to sync with the band. An error saying can’t sync appears in mi band and the app frozens having to shut it down (the app) to use it again. 
Can’t install new watch faces 

**To Reproduce**
1. Go to ‘AmazTools '
2. Click on ‘Transfers '
3. Choose de watch face and click install
4. Tries to sync (appears sync in Mi band) then error saying can’t sync (also appears in band)
5. App AmazTools is now frozen and has to be shut down manually 

**Device info (please complete the following information):**
 - OS: [14.7.1]
 - Device [iPhone XR]
 - App Version and Build number [e.g. v1.2.4 (424)]
 - Mi Band 6

**Additional context**
When starting the AmazTools app also appears in band saying I have to update to latest version. This happens when using both versions (App Store and TestFlight)

**Comment by MattiaFochesato** [comment]
I am aware of the problem and we're working to fix it as soon as possible. Unfortunately, there has been a radical change in the comunication protocol and it seems quite complex to implement.

**Comment by MattiaFochesato** [comment]
A new beta has been released. Please check it out.
