### ISSUE TITLE
[FEATURE REQUEST] Apple Music Control

### ISSUE THREAD

**Issue by snjyr123** [MattiaFochesato/AmazTools#8]
**Is your feature request related to a problem? Please describe.**
Apple Music is a great feature to add to Amaztools, as the in built Amazfit music controls need improvement.

**Describe the solution you'd like**
Something like the old Spotify widget that used to be on Amaztools

**Comment by MattiaFochesato** [comment]
Unfortunately, the new devices no longer send a signal at the push of a button.

In addition, Apple Music has no public API to be able to control the playback of songs. It is not even possible to control local playback (this is an iOS limitation).
