### ISSUE TITLE
[FEATURE] Sync calendar events

### ISSUE THREAD

**Issue by Marcel1202** [MattiaFochesato/AmazTools#9]
There is a feature in the app to sync reminders. However, this only syncs reminders with a deadline, since the watch only has a schedule app not a reminder one. Wouldn‘t it make a even more sense to allow syncing calendar events?

**Comment by MattiaFochesato** [comment]
I think it is a good observation.
I'm going to leave the reminder synchronization but I'll also add the native calendar sync.
Thank you for your suggestion!
